/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        background: "#f4f6f8",
        surface: "#ffffff",
        "surface-dim": "#eef2f4",
        "surface-tint": "#c41f2b",
        "surface-variant": "#d8dfe4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f9fb",
        "surface-container": "#edf2f6",
        "surface-container-high": "#e4eaef",
        "surface-container-highest": "#dae2e8",
        "inverse-surface": "#0f1720",
        primary: "#af101a",
        "primary-fixed": "#ff6b74",
        "on-primary": "#ffffff",
        "primary-container": "#ffd8db",
        "on-primary-container": "#5e0710",
        "inverse-primary": "#ffb3b9",
        secondary: "#4b5b68",
        "secondary-container": "#d3e4f3",
        tertiary: "#11651d",
        "tertiary-container": "#d5f4d8",
        "on-tertiary-container": "#0a3c11",
        "tertiary-fixed": "#89e197",
        "tertiary-fixed-dim": "#4db562",
        "secondary-fixed-dim": "#b9c7d4",
        error: "#c62828",
        "on-error": "#ffffff",
        "error-container": "#fde2e2",
        "on-error-container": "#7a1111",
        outline: "#8a98a5",
        "outline-variant": "#c9d3da",
        "on-surface": "#17212b",
        "on-surface-variant": "#5a6773",
        "inverse-on-surface": "#eff4f8",
      },
      spacing: {
        unit: "0.25rem",
        "stack-sm": "0.75rem",
        "stack-md": "1rem",
        "stack-lg": "1.5rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2rem",
        gutter: "2rem",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["0.75rem", { lineHeight: "1rem" }],
        "label-md": ["0.875rem", { lineHeight: "1.25rem" }],
        "body-md": ["1rem", { lineHeight: "1.5rem" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.6rem" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem" }],
        "headline-lg": ["2rem", { lineHeight: "2.5rem" }],
        "headline-lg-mobile": ["1.75rem", { lineHeight: "2.15rem" }],
        "display-lg": ["3.75rem", { lineHeight: "4rem" }],
      },
      boxShadow: {
        panel: "0 20px 50px rgba(15, 23, 42, 0.12)",
        overlay: "0 30px 80px rgba(15, 23, 42, 0.18)",
      },
      maxWidth: {
        "screen-panel": "80rem",
      },
      keyframes: {
        "soft-pulse": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.55" },
          "50%": { transform: "scale(1.08)", opacity: "1" },
        },
        "pulse-ring": {
          "0%": { transform: "scale(0.9)", opacity: "0.7" },
          "70%": { transform: "scale(1.35)", opacity: "0" },
          "100%": { transform: "scale(1.35)", opacity: "0" },
        },
      },
      animation: {
        "soft-pulse": "soft-pulse 2s ease-in-out infinite",
        "pulse-ring": "pulse-ring 1.8s cubic-bezier(0, 0, 0.2, 1) infinite",
      },
    },
  },
  plugins: [],
};
