# docker-compose.yml
services:
  # 1. THE DATABASE (MongoDB)
  mongodb:
    image: mongo:7
    container_name: snapbulance_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: snapbulance
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  # 2. THE BACKEND (Express + MongoDB)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: snapbulance_backend
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  # 3. THE FRONTEND (React + Vite + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # These are injected DURING the build step (Stage 1 of the Dockerfile)
        - VITE_ENVIRONMENT=development
        - VITE_API_URL_LOCAL=http://localhost:3000/
    container_name: snapbulance_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80" # Maps your 5173 to Nginx's internal port 80

# Define the virtual hard drives
volumes:
  mongodata:
